### ISSUE TITLE
Segmantation fault on jrctl

### ISSUE THREAD

**Issue by mekanix** [cbsd/cbsd#422]
Mandatory info for bug reports:
`cbsd jrctl` last line states `Segmentation fault`

FreeBSD version ( uname -a ): 
12.0-RELEASE-p8

CBSD version ( cbsd version ): 
12.0.13

The weird thing is that I have a machine which works but it was updated to the same version as stated above, but if those version are used to initialize CBSD for the first time, `cbsd jrctl` segfaults after the last line!? I added simple echo statement at the end of `jailctl/jrctl`, and segfault is after it.

**Comment by olevole** [comment]
yes, this is a well-known issue for me, related to 
'. ${sharedir}/rctl.conf'

strings and

this code: https://github.com/cbsd/cbsd/blob/develop/bin/cbsdsh/input.c#L363-L395

in fact, the last line in 'jrctl' script should be:

`exit 0`

I think this should fix the problem.

**Comment by mekanix** [comment]
That solves it partially. I still get
```
No such /usr/cbsd/jails-system/jail1/helpers/jrctl.sqlite
No /usr/cbsd/modules/forms.d/jrctl/initforms.sh
No such /usr/cbsd/jails-system/jail1/helpers/jrctl.sqlite
set_error
```
on `jstart`. Where do the sqlite and initforms should come? I suppose jconstruct{,-tui}? I would really like to track down where this is coming from.

**Comment by olevole** [comment]
Yes, that is another problem. I haven't found the time to look at it yet.

**Comment by mekanix** [comment]
I'll try to bisect it and at least find the faulty commit

**Comment by mekanix** [comment]
This is what `git reflog` reports:
```
ea083e90 (tag: v12.0.8, origin/12.0.8, refs/bisect/bad) HEAD@{2}: checkout: moving from 3d09819fa9e113f3efb6c12fea19e2023685edcc to ea083e9094ccb2a4d73d8d6d9e64bd4c0bdbf82c
3d09819f HEAD@{3}: checkout: moving from b55ff48a37486b4c815f0bfa59c98aa5ad40bb42 to 3d09819fa9e113f3efb6c12fea19e2023685edcc
b55ff48a (refs/bisect/good-b55ff48a37486b4c815f0bfa59c98aa5ad40bb42) HEAD@{4}: checkout: moving from 8a1ac4ddf0474a8af085c874befdc1ad0e291e55 to b55ff48a37486b4c815f0bfa59c98aa5ad40bb42
8a1ac4dd (refs/bisect/good-8a1ac4ddf0474a8af085c874befdc1ad0e291e55) HEAD@{5}: checkout: moving from 6f25ca49efd7c6df8747bc9d91087b65f66263b0 to 8a1ac4ddf0474a8af085c874befdc1ad0e291e55
6f25ca49 (refs/bisect/good-6f25ca49efd7c6df8747bc9d91087b65f66263b0) HEAD@{6}: checkout: moving from dc6166ef6c715fd8e639703d39670268e9f04e6d to 6f25ca49efd7c6df8747bc9d91087b65f66263b0
dc6166ef HEAD@{7}: checkout: moving from 836f5c0685ee3c6406a22f67987f489cb50eda79 to dc6166ef6c715fd8e639703d39670268e9f04e6d
836f5c06 (refs/bisect/good-836f5c0685ee3c6406a22f67987f489cb50eda79) HEAD@{8}: checkout: moving from 7a4f06ae04811cad5bc47e63f63e76173c28f750 to 836f5c0685ee3c6406a22f67987f489cb50eda79
7a4f06ae (refs/bisect/good-7a4f06ae04811cad5bc47e63f63e76173c28f750) HEAD@{9}: checkout: moving from 730bf6b76e361607f21f69efa8ec93a589abdd05 to 7a4f06ae04811cad5bc47e63f63e76173c28f750
730bf6b7 HEAD@{10}: checkout: moving from develop to 730bf6b76e361607f21f69efa8ec93a589abdd05
```

What I got with `git bisect` is
```
ea083e9094ccb2a4d73d8d6d9e64bd4c0bdbf82c is the first bad commit
```

Well, something to start with! :o)

**Comment by mekanix** [comment]
The helper script I used to reinitialize CBSD:
```
#!/bin/sh

service cbsdd stop
service cbsdrsyncd stop
killall -9 cbsd
zfs destroy -r zroot/usr/cbsd
chflags -R noschg /usr/cbsd
rm -rf /usr/cbsd
zfs create -o mountpoint=/usr/cbsd zroot/usr/cbsd
env workdir=/usr/cbsd /usr/local/cbsd/sudoexec/initenv
service cbsdd restart
service cbsdrsyncd restart
```

**Comment by mekanix** [comment]
It didn't make sanse to me what bisect returned as an answer so I started checking commits between v12.0.17 (it should have been v12.0.7, error in the versioning) and v12.0.8:
```
7b9ad6a4885691339acbe7f1a690657e51100d90 good
c0a7da0f9160ec3939e9c47035c05447a49ef211 bad
```

**Comment by mekanix** [comment]
That's one huge commit. @oleg, can you shine some light? Is segfault dumping core? If yes, where do you think I can find cbsd.core or similar file?

**Comment by olevole** [comment]
by default, core file drops into cwd directory for process. you can change this behavior by kern.corefile mask, e.g:

```
sysctl -w kern.corefile="/var/coredumps/%N.core"
sysctl -w kern.sugid_coredump=1 
```

and create dirs for core:
```
mkdir /var/coredumps
chmod 0777
```

**Comment by olevole** [comment]
git diff-tree -p c0a7da0f9160ec3939e9c47035c05447a49ef211 

^^ hmm, this commit removes historical duplicate files in $workdir  ( this work is also related to support multiple workdir environment by *cbsd* ) but I still do not understand what is the cause of segfault ;-(

Also I was forced to use the exit at the end the script to correct the same behavior in *updatesql* https://github.com/cbsd/cbsd/issues/371

**Comment by olevole** [comment]
... One big commit is bad, but it was connected with the fact that I worked offline for a while on my laptop and periodically forgot to commits. I will try not to do this anymore ;-)

**Comment by olevole** [comment]
Thx!
